version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./testutils/Dockerfile
    command: just server
    environment:
      APP_ENV: dev
      LOG_LEVEL: info
      POSTGRES_DB: svcdb
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_VERSION: 14
    ports:
      - 50051:50051
    volumes:
      - .:/app
      - /app/vendor

  db:
    image: postgres:14
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 55432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
